const DEFAULT_MARKET_API_URL="./data/market.json";
const DEFAULT_ASSET_API_URL="./data/assets.json";
const STORAGE_KEYS={marketApiUrl:"fp_v3_market_api",assetApiUrl:"fp_v3_asset_api",riskFirst:"fp_v3_risk_first",autoRefresh:"fp_v3_auto_refresh",lastMarketData:"fp_v3_last_market",lastAssetData:"fp_v3_last_assets"};
let appState={deferredPrompt:null,autoRefreshTimer:null,marketData:null,assetsData:null};
const $=id=>document.getElementById(id);
function escapeHtml(value=""){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function clamp(v,min,max){return Math.max(min,Math.min(max,Number(v)||0))}
function badgeClass(level){const t=String(level||"").toLowerCase();if(t.includes("高")||t.includes("强")||t.includes("达标"))return "";if(t.includes("中")||t.includes("观察")||t.includes("跟踪")||t.includes("未达"))return "warn";if(t.includes("风险")||t.includes("弱")||t.includes("低")||t.includes("不达")||t.includes("预警"))return "hot";return "blue"}
function trendClass(v){const t=String(v||"");if(t.includes("+")||t.includes("强")||t.includes("修复")||t.includes("开启")||t.includes("升"))return "up";if(t.includes("-")||t.includes("弱")||t.includes("降")||t.includes("跌"))return "down";return "flat"}
function scoreClass(score){if(score>=75)return "up";if(score>=55)return "flat";return "down"}
function getMarketApiUrl(){return localStorage.getItem(STORAGE_KEYS.marketApiUrl)||DEFAULT_MARKET_API_URL}
function getAssetApiUrl(){return localStorage.getItem(STORAGE_KEYS.assetApiUrl)||DEFAULT_ASSET_API_URL}
function buildUrl(url,symbol){if(symbol&&url.includes("{symbol}"))return url.replaceAll("{symbol}",encodeURIComponent(symbol));return url}
function showToast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function setLoading(btn,loading){if(!btn)return;btn.disabled=loading;btn.style.opacity=loading?".65":"1"}
async function fetchJson(url){const u=url+(url.includes("?")?"&":"?")+"t="+Date.now();const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}
function setScoreRing(score){const pct=clamp(score,0,100);$("decisionScore").textContent=Math.round(pct);$("scoreRing").style.background=`conic-gradient(var(--green) 0 ${pct}%, rgba(255,255,255,.1) ${pct}% 100%)`}
async function fetchMarketData(){const btn=$("refreshBtn");setLoading(btn,true);try{$("dataStatus").textContent="更新中";const data=await fetchJson(getMarketApiUrl());if(!data.market)throw new Error("缺少 market 字段");localStorage.setItem(STORAGE_KEYS.lastMarketData,JSON.stringify(data));appState.marketData=data;renderMarket(data,false);showToast("市场数据已更新")}catch(e){const cached=localStorage.getItem(STORAGE_KEYS.lastMarketData);if(cached){const data=JSON.parse(cached);appState.marketData=data;renderMarket(data,true);showToast("市场数据失败，已使用缓存")}else{renderMarketError(e);showToast("市场数据加载失败")}}finally{setLoading(btn,false)}}
function renderMarket(data,fromCache=false){const market=data.market||{},decision=data.decision||{},indices=data.indices||[],homeSignals=data.homeSignals||[],tracks=data.tracks||[],hotThemes=data.hotThemes||[],hotNews=data.hotNews||[],radar=data.radar||{},risks=data.risks||[];$("marketMode").textContent=market.mode||"暂无结论";$("marketSummary").textContent=market.summary||"暂无市场摘要";$("aiConclusion").textContent=decision.conclusion||"暂无作战结论";$("radarScore").textContent=radar.score??decision.score??"--";$("disciplineText").textContent=radar.discipline||"暂无纪律提示";$("dataStatus").textContent=fromCache?"缓存":"动态";$("hotUpdateTime").textContent=formatTime(data.updatedAt);$("lastUpdatedText").textContent=formatTime(data.updatedAt);$("subTitle").textContent=data.subtitle||"V3 高置信决策 · 风控优先";setScoreRing(decision.score??radar.score??0);
$("indexRow").innerHTML=indices.slice(0,3).map(x=>`<div class="index-card"><span>${escapeHtml(x.name)}</span><b class="${trendClass(x.value)}">${escapeHtml(x.value)}</b></div>`).join("");
$("homeSignals").innerHTML=homeSignals.map(x=>`<div class="mini-card"><div class="emoji">${escapeHtml(x.icon||"📌")}</div><h4>${escapeHtml(x.title)}</h4><p>${escapeHtml(x.text)}</p></div>`).join("");
$("trackList").innerHTML=tracks.map(renderTrack).join("");$("heatBars").innerHTML=hotThemes.map(renderHeatBar).join("");$("hotNews").innerHTML=hotNews.map(renderNewsCard).join("");
$("radarCards").innerHTML=(radar.cards||[]).map(c=>`<div class="panel-card"><div class="emoji">${escapeHtml(c.icon||"📌")}</div><h4>${escapeHtml(c.title)}</h4><p>${escapeHtml(c.text)}</p></div>`).join("");
$("riskList").innerHTML=risks.map(r=>`<article class="risk-item"><h4>${escapeHtml(r.title)} <span class="badge ${badgeClass(r.level)}">${escapeHtml(r.level||"提示")}</span></h4><p>${escapeHtml(r.text)}</p></article>`).join("")}
function renderTrack(t){const rules=t.rules||[];return `<article class="decision-card"><div class="decision-head"><div><h4>${escapeHtml(t.icon||"🧭")} ${escapeHtml(t.name)}</h4><p>${escapeHtml(t.logic||"")}</p></div><span class="badge ${badgeClass(t.tag)}">${escapeHtml(t.tag||"观察")}</span></div><div class="metric-grid"><div class="metric"><span>赛道分</span><b class="${Number(t.score)>=75?"up":"flat"}">${escapeHtml(t.score??"--")}</b></div><div class="metric"><span>入场</span><b>${escapeHtml(t.entry||"--")}</b></div><div class="metric"><span>风险</span><b class="${String(t.risk).includes("高")?"down":"flat"}">${escapeHtml(t.risk||"--")}</b></div></div><ul class="rule-list">${rules.map(r=>`<li class="${escapeHtml(r.type||"")}">${escapeHtml(r.text||r)}</li>`).join("")}</ul></article>`}
function renderHeatBar(t){const s=clamp(t.score,0,100);return `<div class="bar-row"><div class="bar-top"><span>${escapeHtml(t.name)}</span><span>${s}</span></div><div class="bar-track"><div class="bar-fill" style="width:${s}%"></div></div></div>`}
function renderNewsCard(x){return `<article class="sector"><div class="icon">${escapeHtml(x.icon||"📰")}</div><div><h4>${escapeHtml(x.title)}</h4><p>${escapeHtml(x.text)}</p></div><div class="badge ${badgeClass(x.tag)}">${escapeHtml(x.tag||"跟踪")}</div></article>`}
function renderMarketError(e){$("marketMode").textContent="数据加载失败";$("marketSummary").textContent="请检查市场 API 或 data/market.json";$("aiConclusion").textContent=e.message||"未知错误";$("dataStatus").textContent="错误"}
async function loadAssetUniverse(){try{const data=await fetchJson(buildUrl(getAssetApiUrl()));appState.assetsData=data;localStorage.setItem(STORAGE_KEYS.lastAssetData,JSON.stringify(data));populateAssetSelect(data);return data}catch(e){const cached=localStorage.getItem(STORAGE_KEYS.lastAssetData);if(cached){const data=JSON.parse(cached);appState.assetsData=data;populateAssetSelect(data);return data}throw e}}
function populateAssetSelect(data){const select=$("symbolSelect");const assets=data.assets||{};const keys=Object.keys(assets);select.innerHTML=keys.map(sym=>{const item=assets[sym];return `<option value="${escapeHtml(sym)}">${escapeHtml(sym)} - ${escapeHtml(item.name||sym)}</option>`}).join("");if(!keys.length)select.innerHTML=`<option value="">未发现资产数据</option>`}
async function runAssetDecision(){const btn=$("runDecisionBtn");setLoading(btn,true);const input=$("symbolInput").value.trim().toUpperCase();const selected=$("symbolSelect").value;const symbol=input||selected;try{if(!symbol)throw new Error("请先输入或选择一个标的。");let data=appState.assetsData||await loadAssetUniverse();let asset=data.assets?.[symbol];if(!asset){const single=await fetchJson(buildUrl(getAssetApiUrl(),symbol));asset=single.asset||single}if(!asset||!asset.prices)throw new Error("没有找到该标的或缺少历史行情。");const result=window.FPDecisionModel.analyzeAsset(asset,{targetWinRate:Number($("targetWinRate").value),forwardDays:Number($("forwardDays").value),costBps:Number($("costBps").value),minSignals:Number($("minSignals").value),stopLossPct:Number($("stopLossPct").value),regimeFilter:$("regimeFilter").value});renderAssetDecision(result);showToast("模型计算完成")}catch(e){$("decisionOutput").innerHTML=`<section class="ai-card"><h3>无法生成决策</h3><p>${escapeHtml(e.message)}</p></section>`;showToast("标的分析失败")}finally{setLoading(btn,false)}}
function sparkline(values){if(!values||values.length<2)return "";const w=320,h=74,pad=8;const min=Math.min(...values),max=Math.max(...values);const range=max-min||1;const pts=values.map((v,i)=>{const x=pad+i*(w-pad*2)/(values.length-1);const y=h-pad-(v-min)*(h-pad*2)/range;return `${x.toFixed(1)},${y.toFixed(1)}`}).join(" ");return `<svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2.5" opacity=".9"/><line x1="0" y1="${h-pad}" x2="${w}" y2="${h-pad}" stroke="rgba(255,255,255,.15)" stroke-width="1"/></svg>`}
function renderAssetDecision(r){const periods=r.periodResults.map(p=>`<div class="period-card"><span>${escapeHtml(p.label)}</span><b class="${scoreClass(p.score)}">${p.score}</b><p>收益 ${p.returnPct.toFixed(2)}%</p><p>回撤 ${p.maxDrawdownPct.toFixed(2)}%</p><p>波动 ${p.volatilityPct.toFixed(2)}%</p></div>`).join("");const bt=r.backtest;$("decisionOutput").innerHTML=`<section class="decision-card result-card"><div class="decision-head"><div><h4>${escapeHtml(r.symbol)} - ${escapeHtml(r.name)}</h4><p>最新交易日：${escapeHtml(r.latestDate)} ｜ 最新价：${Number(r.latestClose).toFixed(2)}</p></div><span class="badge ${badgeClass(r.level)}">${escapeHtml(r.level)}</span></div>${sparkline(r.sparkline)}<div class="big-score"><div><span>综合分</span><b class="${scoreClass(r.scores.decisionScore)}">${r.scores.decisionScore}</b></div><div><span>建议</span><b>${escapeHtml(r.action)}</b></div><div><span>仓位</span><b>${escapeHtml(r.position)}</b></div></div><div class="metric-grid"><div class="metric"><span>趋势</span><b class="${scoreClass(r.scores.trendScore)}">${r.scores.trendScore}</b></div><div class="metric"><span>动量</span><b class="${scoreClass(r.scores.momentumScore)}">${r.scores.momentumScore}</b></div><div class="metric"><span>风险</span><b class="${scoreClass(r.scores.riskScore)}">${r.scores.riskScore}</b></div></div><section class="ai-card"><h3>walk-forward 回测</h3><p>信号 ${bt.total} 次｜命中 ${bt.wins} 次｜胜率 ${(bt.winRate*100).toFixed(1)}%｜Wilson下界 ${(bt.wilsonLowerBound*100).toFixed(1)}%｜PF ${bt.profitFactor.toFixed(2)}｜最大连亏 ${bt.maxConsecutiveLosses}｜平均净收益 ${bt.avgNetReturn.toFixed(2)}%｜止损 ${bt.stopLossPct}%</p></section><section class="quality-box"><h4>数据质量</h4><p>${r.dataQuality&&r.dataQuality.ok?"数据质量检查通过。":"数据质量存在问题："+escapeHtml((r.dataQuality?.issues||[]).join("；"))}</p></section><div class="period-grid">${periods}</div><h4 class="subhead">入场条件</h4><ul class="rule-list">${r.entryRules.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul><h4 class="subhead">阻断/风险原因</h4><ul class="rule-list">${r.warnings.map(x=>`<li class="risk">${escapeHtml(x)}</li>`).join("")}</ul><p class="disclaimer">这是量化辅助模型输出，不构成证券投资建议。90% 是历史回测筛选门槛，不是未来保证。</p></section>`}
function formatTime(v){if(!v)return"--";try{const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return d.toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}catch{return v}}
function initNavigation(){document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>{const p=btn.dataset.page;document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===p));document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.page===p));window.scrollTo({top:0,behavior:"smooth"});history.replaceState(null,"","#"+p)}));const h=location.hash.replace("#","");if(h&&document.getElementById(h))document.querySelector(`.nav-item[data-page="${h}"]`)?.click()}

async function runDiagnostics(){
  const set=(id,text,cls)=>{const el=$(id); if(el){el.textContent=text; el.className=cls||"";}};
  async function test(url){
    try{
      const r=await fetch(url+(url.includes("?")?"&":"?")+"diag="+Date.now(),{cache:"no-store"});
      if(!r.ok)return "HTTP "+r.status;
      await r.json();
      return "正常";
    }catch(e){return "失败";}
  }
  const m=await test("./data/market.json");
  const a=await test("./data/assets.json");
  set("diagMarket",m,m==="正常"?"up":"down");
  set("diagAssets",a,a==="正常"?"up":"down");
  set("diagSW","serviceWorker" in navigator ? "支持" : "不支持","serviceWorker" in navigator ? "up":"down");
  set("diagCache","V4","up");
  showToast(m==="正常"&&a==="正常"?"数据路径正常":"数据路径存在问题");
}
async function clearLocalCache(){
  Object.values(STORAGE_KEYS).forEach(k=>localStorage.removeItem(k));
  if("caches" in window){
    const keys=await caches.keys();
    await Promise.all(keys.map(k=>caches.delete(k)));
  }
  showToast("本地缓存已清理，请刷新页面");
}

function initSettings(){$("marketApiUrlInput").value=getMarketApiUrl();$("assetApiUrlInput").value=getAssetApiUrl();$("saveMarketApiBtn").onclick=()=>{localStorage.setItem(STORAGE_KEYS.marketApiUrl,$("marketApiUrlInput").value.trim()||DEFAULT_MARKET_API_URL);fetchMarketData()};$("resetMarketApiBtn").onclick=()=>{localStorage.removeItem(STORAGE_KEYS.marketApiUrl);$("marketApiUrlInput").value=DEFAULT_MARKET_API_URL;fetchMarketData()};$("saveAssetApiBtn").onclick=async()=>{localStorage.setItem(STORAGE_KEYS.assetApiUrl,$("assetApiUrlInput").value.trim()||DEFAULT_ASSET_API_URL);appState.assetsData=null;await loadAssetUniverse();showToast("资产数据源已保存")};$("resetAssetApiBtn").onclick=async()=>{localStorage.removeItem(STORAGE_KEYS.assetApiUrl);$("assetApiUrlInput").value=DEFAULT_ASSET_API_URL;appState.assetsData=null;await loadAssetUniverse();showToast("资产数据源已恢复")};document.querySelectorAll(".switch").forEach(sw=>{const key=sw.dataset.setting;const sk=key==="riskFirst"?STORAGE_KEYS.riskFirst:STORAGE_KEYS.autoRefresh;if(localStorage.getItem(sk)==="false")sw.classList.remove("on");sw.onclick=()=>{sw.classList.toggle("on");localStorage.setItem(sk,sw.classList.contains("on")?"true":"false");setupAutoRefresh()}});
if($("runDiagBtn"))$("runDiagBtn").onclick=runDiagnostics;
if($("clearCacheBtn"))$("clearCacheBtn").onclick=clearLocalCache;
}
function setupInstallButton(){window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();appState.deferredPrompt=e});$("installBtn").onclick=async()=>{if(appState.deferredPrompt){appState.deferredPrompt.prompt();await appState.deferredPrompt.userChoice;appState.deferredPrompt=null}else showToast("请用浏览器菜单添加到主屏幕")}}
function setupAutoRefresh(){if(appState.autoRefreshTimer)clearInterval(appState.autoRefreshTimer);if(localStorage.getItem(STORAGE_KEYS.autoRefresh)!=="false")appState.autoRefreshTimer=setInterval(()=>fetchMarketData(),5*60*1000)}
function registerServiceWorker(){if("serviceWorker"in navigator)window.addEventListener("load",async()=>{try{const reg=await navigator.serviceWorker.register("./sw.js");if(reg.waiting)reg.waiting.postMessage({type:"SKIP_WAITING"})}catch(e){console.warn(e)}})}
async function initApp(){initNavigation();initSettings();setupInstallButton();setupAutoRefresh();$("refreshBtn").onclick=()=>fetchMarketData();$("runDecisionBtn").onclick=runAssetDecision;$("symbolInput").addEventListener("keydown",e=>{if(e.key==="Enter")runAssetDecision()});await fetchMarketData();try{await loadAssetUniverse()}catch(e){showToast("资产数据源加载失败")}registerServiceWorker()}
document.addEventListener("DOMContentLoaded",initApp);
